# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f87dbc59582d4d0bbdc4b12690ecfca3244db4703b73a046b339ea5767fd223991ada711a7e6b3d567699c2bd0cba7ed8aeba5a05eb95053a33eb49c10b1c839

test:
  secret_key_base: d7ded69ed5a36b8f3c08f245d0b3ebc1893c94c6f9c6d4931483ff6490ce00df4628c20b82a569d77bd37c0d0fc68f059ddbcd559885472f8252be25f4582244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
